### ISSUE TITLE
Add plugin/hoc shorthand

### ISSUE THREAD

**Issue by rasmusprentow** [fusionjs/fusion-react#106]
### Type of issue

Feature request 

### Description
The current pattern for creating provider/HOC pairs is not optimal: Current solution: 
```
export const Plugin = ProviderPlugin.create('console', plugin);
export const HOC = ProvidedHOC.create('console');
```
It would be nice if they could be specified using a single method such as: 

```
const {hoc, provider} = createHOCPluginPair('console', plugin);
```
The big benefit here is that it can be typed such that `hoc` actually contains type information about console. In the current solution the type information is lost when `ProvidedHOC.create` is called.

**Comment by rtsao** [comment]
We will eventually need to refactor this to use the [React 16.3 `React.createContext` API](https://reactjs.org/docs/context.html#reactcreatecontext), which is the first "officially" supported version of context. The old API will continue work for all 16.x releases, but it's essentially deprecated now.

This would eliminate the string keys part of this API altogether, so I think this API will need to change to accommodate that, perhaps something that resembles the API you suggest.

I think one option is to remove `providedHOC` and `ProviderPlugin` all together in favor of something that looks like this:

```js
const {Provider, Consumer} = React.createContext(defaultValue);
const plugin = createWrapperPlugin(Provider);
```

Because the typing of Provider/Consumer from `React.createContext` is essentially "built-in" so we don't need to do anything special to make it work. Furthermore, `createWrapperPlugin` could simply take any component and wraps the root component in it. It doesn't have to know anything about context at all, so it's a bit more general purpose. There's also less obfuscation of what's happening under the hood with context so I think it's much more clear how everything works.

**Comment by rasmusprentow** [comment]
Fixed by: https://github.com/fusionjs/fusion-react/pull/163
